import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        outline: "#a08e7a",
        "outline-variant": "#534434",
        "on-primary-fixed-variant": "#653e00",
        "primary-fixed": "#ffddb8",
        surface: "#111319",
        "surface-container-high": "#282a30",
        "on-error": "#690005",
        "surface-container-low": "#191b22",
        "primary-fixed-dim": "#ffb95f",
        "on-primary-container": "#613b00",
        "on-error-container": "#ffdad6",
        "surface-variant": "#33343b",
        "secondary-container": "#e3aa00",
        "surface-bright": "#373940",
        "on-secondary-container": "#5a4100",
        "error-container": "#93000a",
        "surface-tint": "#ffb95f",
        error: "#ffb4ab",
        "on-tertiary-container": "#574000",
        "tertiary-fixed": "#ffdf9a",
        "inverse-on-surface": "#2e3037",
        "on-surface": "#e2e2ea",
        "on-tertiary-fixed": "#251a00",
        "on-tertiary": "#3f2e00",
        "on-primary": "#472a00",
        "inverse-surface": "#e2e2ea",
        "on-secondary-fixed": "#261a00",
        background: "#111319",
        "secondary-fixed-dim": "#f9bd22",
        tertiary: "#fdc425",
        "tertiary-fixed-dim": "#f7be1d",
        secondary: "#ffc640",
        "inverse-primary": "#855300",
        primary: "#ffc174",
        "on-tertiary-fixed-variant": "#5a4300",
        "on-surface-variant": "#d8c3ad",
        "on-background": "#e2e2ea",
        "on-secondary-fixed-variant": "#5c4300",
        "surface-container-lowest": "#0c0e14",
        "surface-container": "#1d1f26",
        "primary-container": "#f59e0b",
        "secondary-fixed": "#ffdf9f",
        "on-primary-fixed": "#2a1700",
        "tertiary-container": "#dea900",
        "surface-container-highest": "#33343b",
        "on-secondary": "#402d00",
        "surface-dim": "#111319",
        // Semantic status tokens
        "status-active": "#F59E0B",
        "status-intervened": "#3B82F6",
        "status-suspected": "#A855F7",
        "status-confirmed": "#10B981",
        "status-relapsed": "#EF4444",
        "brand-lime": "#c2fb4d",
        "brand-indigo": "#6366f1",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        "gutter-mobile": "1rem",
        "margin-mobile": "1rem",
        "space-xl": "2.5rem",
        margin: "2rem",
        "margin-sm": "1rem",
        "space-md": "1rem",
        "space-sm": "0.5rem",
        "space-xs": "0.25rem",
        gutter: "1.5rem",
        "space-lg": "1.5rem",
      },
      fontFamily: {
        sans: ["Inter", "sans-serif"],
        mono: ["JetBrains Mono", "monospace"],
        "headline-sm": ["Inter", "sans-serif"],
        "body-sm": ["Inter", "sans-serif"],
        "label-sm": ["Inter", "sans-serif"],
        "label-md": ["Inter", "sans-serif"],
        "code-md": ["JetBrains Mono", "monospace"],
        "display-hero-mobile": ["Inter", "sans-serif"],
        "display-hero": ["Inter", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "headline-lg": ["Inter", "sans-serif"],
        "headline-md": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "code-sm": ["JetBrains Mono", "monospace"],
        "headline-lg-mobile": ["Inter", "sans-serif"],
      },
      fontSize: {
        "headline-sm": ["18px", { lineHeight: "26px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "body-sm": ["12px", { lineHeight: "18px", fontWeight: "400" }],
        "label-sm": ["11px", { lineHeight: "16px", letterSpacing: "0.04em", fontWeight: "600" }],
        "label-md": ["13px", { lineHeight: "18px", letterSpacing: "0.01em", fontWeight: "500" }],
        "code-md": ["13px", { lineHeight: "22px", fontWeight: "400" }],
        "display-hero-mobile": ["32px", { lineHeight: "40px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "display-hero": ["48px", { lineHeight: "56px", letterSpacing: "-0.03em", fontWeight: "700" }],
        "body-lg": ["16px", { lineHeight: "26px", fontWeight: "400" }],
        "headline-lg": ["32px", { lineHeight: "40px", letterSpacing: "-0.02em", fontWeight: "600" }],
        "headline-md": ["24px", { lineHeight: "32px", letterSpacing: "-0.015em", fontWeight: "600" }],
        "body-md": ["14px", { lineHeight: "22px", fontWeight: "400" }],
        "code-sm": ["11px", { lineHeight: "18px", fontWeight: "400" }],
        "headline-lg-mobile": ["24px", { lineHeight: "32px", letterSpacing: "-0.01em", fontWeight: "600" }],
      },
    },
  },
  plugins: [],
};

export default config;
