import type { Item, MisconceptionInfo, ProblemTrack, TraceStep } from "./types";

export const PROBLEMS: Item[] = [
  {
    item_id: "i1",
    kind: "diagnostic",
    family: "indexing",
    title: "List Element Extraction",
    category: "Lists & Indexing",
    difficulty: "Diagnostic",
    company: "Google",
    prompt: "What will this code print?",
    code: "a = [10, 20, 30]\nprint(a[1])",
    problem_ref: "GGL-PY-101",
    expected_output: "20",
    options: ["10", "20", "30", "IndexError"],
    misconceptions_map: {
      "10": "index_1_based",
      "30": "reverse_index",
    },
    explanation: "Python list indices start at 0, not 1. The index represents the offset (memory distance) from the beginning of the list.",
  },
  {
    item_id: "i2",
    kind: "probe",
    family: "mutability",
    title: "Default Argument Mutation",
    category: "Functions & Scope",
    difficulty: "Edge Case",
    company: "Meta",
    prompt: "What will this code print?",
    code: "def add_item(val, bucket=[]):\n    bucket.append(val)\n    return bucket\n\nprint(add_item(1))\nprint(add_item(2))",
    problem_ref: "META-PY-204",
    expected_output: "[1]\n[1, 2]",
    options: ["[1]\n[2]", "[1]\n[1, 2]", "[1, 2]\n[1, 2]", "[2]\n[2]"],
    misconceptions_map: {
      "[1]\n[2]": "recreated_default_arg",
    },
    explanation: "Default parameter expressions in Python are evaluated once when the function is defined, not each time it is called. The list persists in the function object's __defaults__ attribute.",
  },
  {
    item_id: "i3",
    kind: "transfer",
    family: "closures",
    title: "Late-Binding Loop Closures",
    category: "Closures & Scoping",
    difficulty: "Edge Case",
    company: "Amazon",
    prompt: "What will this code print?",
    code: "funcs = [lambda x: x * i for i in range(3)]\nprint([f(2) for f in funcs])",
    problem_ref: "AMZ-PY-315",
    expected_output: "[4, 4, 4]",
    options: ["[0, 2, 4]", "[4, 4, 4]", "[0, 0, 0]", "[2, 4, 6]"],
    misconceptions_map: {
      "[0, 2, 4]": "closure_early_binding",
    },
    explanation: "Python closures look up variables in the enclosing scope when the function is called, not when defined. After the list comprehension finishes, i has the value 2.",
  },
  {
    item_id: "i4",
    kind: "probe",
    family: "strings",
    title: "String In-Place Modification",
    category: "Strings & Immutability",
    difficulty: "Diagnostic",
    company: "Microsoft",
    prompt: "What will this code print?",
    code: 'greeting = "hello"\ngreeting.upper()\nprint(greeting)',
    problem_ref: "MSFT-PY-108",
    expected_output: "hello",
    options: ["HELLO", "hello", "None", "AttributeError"],
    misconceptions_map: {
      HELLO: "noop_method",
    },
    explanation: "Strings in Python are immutable. Methods like .upper() or .replace() return a brand-new string object and leave the original unchanged.",
  },
  {
    item_id: "i5",
    kind: "transfer",
    family: "references",
    title: "Shallow Copy & Nested Aliasing",
    category: "Object References",
    difficulty: "Transfer",
    company: "Stripe",
    prompt: "What will this code print?",
    code: "orig = [1, [2, 3]]\nclone = orig[:]\nclone[1].append(4)\nprint(orig)",
    problem_ref: "STRP-PY-402",
    expected_output: "[1, [2, 3, 4]]",
    options: ["[1, [2, 3]]", "[1, [2, 3, 4]]", "[1, 4, [2, 3]]", "TypeError"],
    misconceptions_map: {
      "[1, [2, 3]]": "assign_copies",
    },
    explanation: "A slice copy orig[:] creates a shallow copy: top-level elements are duplicated, but nested mutable objects remain referenced by memory address.",
  },
  {
    item_id: "i6",
    kind: "discriminator",
    family: "operators",
    title: "Operator Precedence Invariant",
    category: "Compiler Semantics",
    difficulty: "Diagnostic",
    company: "Google",
    prompt: "What will this code print?",
    code: "res = 20 + 10 / 2 * 3\nprint(int(res))",
    problem_ref: "GGL-PY-109",
    expected_output: "35",
    options: ["45", "35", "5", "30"],
    misconceptions_map: {
      "45": "add_before_div",
    },
    explanation: "Multiplication and division have equal precedence and associate left-to-right before addition: 10 / 2 = 5.0, then 5.0 * 3 = 15.0, plus 20 = 35.0.",
  },
];

export const TRACE_STEPS_BY_ITEM: Record<string, TraceStep[]> = {
  i1: [
    {
      step: 1,
      line: 1,
      code: "a = [10, 20, 30]",
      description: "Python allocates memory buffer for 3 integers and assigns pointer reference to 'a'.",
      learner_view: {
        title: "Mental Model: Ordered Container",
        mapping: [
          { label: "Item 1", value: "10", note: "First in container" },
          { label: "Item 2", value: "20", note: "Second in container" },
          { label: "Item 3", value: "30", note: "Third in container" },
        ],
      },
      python_view: {
        title: "CPython PyListObject Allocation",
        offsets: [
          { label: "ob_item[0]", value: "10", note: "base ptr + 0" },
          { label: "ob_item[1]", value: "20", note: "base ptr + 1*size" },
          { label: "ob_item[2]", value: "30", note: "base ptr + 2*size" },
        ],
      },
    },
    {
      step: 2,
      line: 2,
      code: "print(a[1])",
      description: "Evaluation of subscript index 1. Divergence occurs here between natural human counting (ordinal) and pointer offset arithmetic.",
      divergence: true,
      learner_view: {
        title: "Believed Mapping (1-Based Ordinal)",
        mapping: [
          { label: "Slot 1", value: "10", note: "Selected (1st)", selected: true },
          { label: "Slot 2", value: "20", note: "2nd item" },
          { label: "Slot 3", value: "30", note: "3rd item" },
        ],
        output: "10",
      },
      python_view: {
        title: "Actual Memory Offset (0-Based Offset)",
        offsets: [
          { label: "Offset [0]", value: "10", note: "Skip 0 items" },
          { label: "Offset [1]", value: "20", note: "Skip 1 item (Selected)", selected: true },
          { label: "Offset [2]", value: "30", note: "Skip 2 items" },
        ],
        output: "20",
      },
    },
    {
      step: 3,
      line: 2,
      code: "print(a[1]) -> STDOUT",
      description: "Value is flushed to stdout buffer. The output displays divergence clearly.",
      learner_view: {
        title: "Predicted STDOUT",
        mapping: [],
        output: "10",
      },
      python_view: {
        title: "CPython STDOUT",
        offsets: [],
        output: "20",
      },
    },
  ],
  i2: [
    {
      step: 1,
      line: 1,
      code: "def add_item(val, bucket=[]):",
      description: "Function object is created in memory once. The empty list [] is evaluated at def time and bound to __defaults__[0].",
      divergence: true,
      learner_view: {
        title: "Mental Model: Fresh Variable on Call",
        mapping: [
          { label: "Call 1", value: "[]", note: "Fresh list allocated" },
          { label: "Call 2", value: "[]", note: "Fresh list allocated" },
        ],
      },
      python_view: {
        title: "CPython PyFunctionObject",
        offsets: [
          { label: "func.__defaults__[0]", value: "id: 0x7fa9 [ ]", note: "Persists across all calls", selected: true },
        ],
      },
    },
    {
      step: 2,
      line: 5,
      code: "print(add_item(1))",
      description: "First invocation appends 1 into the persistent default list.",
      learner_view: {
        title: "Call 1 Result",
        mapping: [{ label: "Return", value: "[1]", note: "Fresh list returned" }],
        output: "[1]",
      },
      python_view: {
        title: "Default Heap Mutation",
        offsets: [{ label: "0x7fa9", value: "[1]", note: "Mutated in-place" }],
        output: "[1]",
      },
    },
    {
      step: 3,
      line: 6,
      code: "print(add_item(2))",
      description: "Second invocation reuses the same default list object at 0x7fa9 and appends 2!",
      divergence: true,
      learner_view: {
        title: "Call 2 Expected",
        mapping: [{ label: "Return", value: "[2]", note: "Brand new list" }],
        output: "[2]",
      },
      python_view: {
        title: "Reused Default Heap",
        offsets: [{ label: "0x7fa9", value: "[1, 2]", note: "Contains previous calls' items!", selected: true }],
        output: "[1, 2]",
      },
    },
  ],
};

export const COMPANY_TRACKS: ProblemTrack[] = [
  {
    id: "google",
    company: "Google",
    title: "Python Core & Mental Model Track",
    problem_count: 24,
    active: true,
    accent: "#6366f1",
    description: "Memory offsets, slice views, generator states, and runtime invariants evaluated in L4/L5 SWE interviews.",
  },
  {
    id: "meta",
    company: "Meta",
    title: "Runtime Semantics & Reference Graphs",
    problem_count: 22,
    accent: "#38bdf8",
    description: "Mutable defaults, circular references, late-binding closures, and Garbage Collection mechanics.",
  },
  {
    id: "amazon",
    company: "Amazon",
    title: "Core Execution & Variable Scopes",
    problem_count: 19,
    accent: "#f59e0b",
    description: "LEGB scope resolution, global vs nonlocal mutations, and decorator binding patterns.",
  },
  {
    id: "microsoft",
    company: "Microsoft",
    title: "Systems Invariants & Async Mechanics",
    problem_count: 16,
    accent: "#10b981",
    description: "String immutability, async coroutine lifecycle, and generator yield delegation.",
  },
  {
    id: "stripe",
    company: "Stripe",
    title: "Financial Precision & Shallow vs Deep Copying",
    problem_count: 18,
    accent: "#c2fb4d",
    description: "Object aliasing, decimal invariants, dict mutations during iteration, and defensive copying.",
  },
];

export const ACTIVE_MISCONCEPTIONS: MisconceptionInfo[] = [
  {
    id: "index_1_based",
    name: "1-Based Ordinal Indexing",
    description: "Student maps list indices to 1st, 2nd, 3rd ordinal positions rather than 0-based memory distance.",
    state: "suspected_resolved",
    posterior: 0.18,
    posterior_history: [0.91, 0.65, 0.42, 0.18],
    bank_ids: [15, 66],
    evidence: {
      discriminator_passes: 3,
      surface_forms: ["list-indexing", "string-slicing", "tuple-unpacking"],
      delayed_retest: false,
    },
  },
  {
    id: "mutable_default",
    name: "Recreated Default Arguments",
    description: "Student believes default arguments in function signatures are re-instantiated on every call.",
    state: "active",
    posterior: 0.84,
    posterior_history: [0.45, 0.72, 0.84],
    bank_ids: [11, 23],
    evidence: {
      discriminator_passes: 0,
      surface_forms: ["list-default"],
      delayed_retest: false,
    },
  },
  {
    id: "closure_early_binding",
    name: "Early-Binding Closures",
    description: "Student assumes lambda closures capture enclosing loop variables by value immediately upon definition.",
    state: "confirmed_resolved",
    posterior: 0.04,
    posterior_history: [0.88, 0.54, 0.15, 0.04],
    bank_ids: [42],
    evidence: {
      discriminator_passes: 5,
      surface_forms: ["comprehension-lambda", "loop-nested-def"],
      delayed_retest: true,
    },
  },
  {
    id: "assign_copies",
    name: "Assignment Deep Copies",
    description: "Student believes assigning a list or shallow copying duplicates nested mutable child references.",
    state: "intervened",
    posterior: 0.65,
    posterior_history: [0.89, 0.65],
    bank_ids: [13, 55],
    evidence: {
      discriminator_passes: 1,
      surface_forms: ["slice-copy"],
      delayed_retest: false,
    },
  },
  {
    id: "noop_method",
    name: "Immutable Method Mutation",
    description: "Student believes calling .upper(), .lower(), or .strip() modifies string instances in place.",
    state: "confirmed_resolved",
    posterior: 0.02,
    posterior_history: [0.76, 0.38, 0.02],
    bank_ids: [6, 7, 8],
    evidence: {
      discriminator_passes: 4,
      surface_forms: ["str-upper", "str-replace"],
      delayed_retest: true,
    },
  },
];
